---
name: AutoClearLagg
description: Recoded & improved auto clear lagg plugin
main: twisted\autoclearlagg\AutoClearLagg
version: 3.1.0
api:
- 3.0.0
author: Twisted fix support php 7&8 by Github PMMPlugin
website: https://github.com/PMMPlugin/AutoClearLagg

commands:
  aclg:
    description: ""
    
permission:
  aclg:
    description: ""
    default: op
...
